const ACTIONS = {
  TOGGLE_SIDEBAR: "TOGGLE",
  CLOSE_SIDEBAR: "CLOSE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOG_OUT: "LOG_OUT",
  LOAD_PROFILE: "LOAD_PROFILE",
};

export default ACTIONS;
