const ACTIONS = {
  TOGGLE_SIDEBAR: "TOGGLE",
  CLOSE_SIDEBAR: "CLOSE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOG_OUT: "LOG_OUT",
  LOAD_PROFILE: "LOAD_PROFILE",
  POPULAR_VIDEOS_SUCCESS: "POPULAR_VIDEOS_SUCCESS",
  POPULAR_VIDEOS_FAIL: "POPULAR_VIDEOS_FAIL",
  POPULAR_VIDEOS_REQUEST: "POPULAR_VIDEOS_REQUEST",
  SELECTED_VIDEO_SUCCESS: "SELECTED_VIDEO_SUCCESS",
  SELECTED_VIDEO_FAIL: "SELECTED_VIDEO_FAIL",
  SELECTED_VIDEO_REQUEST: "SELECTED_VIDEO_REQUEST",
  RELATED_VIDEOS_SUCCESS: "RELATED_VIDEOS_SUCCESS",
  RELATED_VIDEOS_FAIL: "RELATED_VIDEOS_FAIL",
  RELATED_VIDEOS_REQUEST: "RELATED_VIDEOS_REQUEST",
};

export default ACTIONS;
